name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs_version:
          - '26.3'
          - '27.2'
          - '28.2'
          - '29.1'
          - 'snapshot'
        exclude:
          # Exclude snapshot builds on Windows due to stability issues
          - os: windows-latest
            emacs_version: 'snapshot'

    steps:
    - uses: actions/checkout@v3

    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Install dependencies
      run: make install

    - name: Run tests
      run: make test

    - name: Run linter
      run: make lint

    - name: Check documentation
      run: make checkdoc

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3

    - uses: jcs090218/setup-emacs@master
      with:
        version: '29.1'

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Install dependencies
      run: make install

    - name: Build package
      run: make package

    - name: Upload package artifact
      uses: actions/upload-artifact@v3
      with:
        name: shellter-package
        path: dist/*.tar